// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhlPZPWmP6bSQDGQjjs3dGU76Aiv3Irko',
    appId: '1:662936156493:web:5c0e402e3d7f89d1f0df04',
    messagingSenderId: '662936156493',
    projectId: 'gold-technology',
    authDomain: 'gold-technology.firebaseapp.com',
    storageBucket: 'gold-technology.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yvDTNrisBWWJ9POVuv4xXeL1ey_lK3g',
    appId: '1:662936156493:android:7716b707634802baf0df04',
    messagingSenderId: '662936156493',
    projectId: 'gold-technology',
    storageBucket: 'gold-technology.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABln7jWctip-toGMnZFPijPYANPkRqKXs',
    appId: '1:662936156493:ios:20a59b8f6ce06851f0df04',
    messagingSenderId: '662936156493',
    projectId: 'gold-technology',
    storageBucket: 'gold-technology.firebasestorage.app',
    iosBundleId: 'com.brhan.goldtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABln7jWctip-toGMnZFPijPYANPkRqKXs',
    appId: '1:662936156493:ios:20a59b8f6ce06851f0df04',
    messagingSenderId: '662936156493',
    projectId: 'gold-technology',
    storageBucket: 'gold-technology.firebasestorage.app',
    iosBundleId: 'com.brhan.goldtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhlPZPWmP6bSQDGQjjs3dGU76Aiv3Irko',
    appId: '1:662936156493:web:73c021f60166922df0df04',
    messagingSenderId: '662936156493',
    projectId: 'gold-technology',
    authDomain: 'gold-technology.firebaseapp.com',
    storageBucket: 'gold-technology.firebasestorage.app',
  );
}
