// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKfP5F-NTvZuVSrJsujrTndJuSbXhyi0',
    appId: '1:596841720591:web:256c82ff99e03afd69ec7a',
    messagingSenderId: '596841720591',
    projectId: 'jira-tips',
    authDomain: 'jira-tips.firebaseapp.com',
    storageBucket: 'jira-tips.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJC1FkGLrkbNa2M0UiRhHSwpzQGUPvfQ',
    appId: '1:596841720591:android:8eb59dec7390115169ec7a',
    messagingSenderId: '596841720591',
    projectId: 'jira-tips',
    storageBucket: 'jira-tips.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtBQsbcV04JcK-uPNHNnJSsQihDqZFA2c',
    appId: '1:596841720591:ios:b729929f4021a76e69ec7a',
    messagingSenderId: '596841720591',
    projectId: 'jira-tips',
    storageBucket: 'jira-tips.firebasestorage.app',
    iosBundleId: 'com.brhan.jobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtBQsbcV04JcK-uPNHNnJSsQihDqZFA2c',
    appId: '1:596841720591:ios:b729929f4021a76e69ec7a',
    messagingSenderId: '596841720591',
    projectId: 'jira-tips',
    storageBucket: 'jira-tips.firebasestorage.app',
    iosBundleId: 'com.brhan.jobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaKfP5F-NTvZuVSrJsujrTndJuSbXhyi0',
    appId: '1:596841720591:web:85c3a0ad684a200069ec7a',
    messagingSenderId: '596841720591',
    projectId: 'jira-tips',
    authDomain: 'jira-tips.firebaseapp.com',
    storageBucket: 'jira-tips.firebasestorage.app',
  );
}
